backend:
  name: git-gateway
  branch: main # Branch que vai mexer no repositório

publish_mode: editorial_workflow # Para fazer um esquema de revisão de novas edições
media_folder: "public/uploads" # Onde os arquivos de mídia serão armazenados
public_folder: "/uploads" # Onde a parte de mídia vai poder ser acessada
display_url: https://faiscadesignjr.com.br/ # URL que será mostrado no UI do Netlify

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

search: false
locale: 'pt'

collections:
  - name: "home" # Nome usado da rota
    extension: "json"
    description: "Coleção que vai conter todos as informações da página principal do site da Faísca."
    label: "Página principal" # Nome usado na label do Netlify 
    folder: "content/homePage" # Local da pasta onde vão estar os arquivos
    slug: "homePage"
    create: true # Permite que usuários criem arquivos nesse local
    editor:
      preview: false
    fields: # Campos disponíveis no Netlify
      - label: "Nossos serviços" 
        name: "servicos_home" 
        widget: "list"
        min: 1 
        max: 7
        fields: 
        - {label: "Serviço", name: "servico", widget: "relation", collection: "servicos", search_fields: ["servico"], value_field: "{{servico}}"}
      
      - label: "Projetos em destaque"
        name: "projetos_home"
        collapsed: false
        widget: "list"
        min: 1
        max: 5
        fields:
          - {label: "Projeto", name: "projeto_destaque", widget: "relation", collection: "projetos", search_fields: ["nome_projeto"], value_field: "{{nome_projeto}}", display_fields: ["{{nome_projeto}}"]}

      - label: "Projetos para o carrossel"
        name: "projetos_carrossel"
        collapsed: false
        widget: "list"
        min: 1
        max: 5
        fields:
          - {label: "Projeto", name: "projeto_carrossel", widget: "relation", collection: "projetos", search_fields: ["nome_projeto"], value_field: "{{nome_projeto}}", display_fields: ["{{nome_projeto}}"]}

  - name: "portfolio" # Nome usado da rota
    extension: "json"
    description: "Coleção que vai conter as informação da pagina de portfólio do site da Faísca."
    label: "Porfólio" # Nome usado na label do Netlify 
    folder: "content/portfolio" # Local da pasta onde vão estar os arquivos
    slug: "portfolioPage"
    create: true # Permite que usuários criem arquivos nesse local
    editor:
      preview: false
    fields: # Campos disponíveis no Netlify
      - label: "Grandes projetos" 
        name: "portfolio_projetos" 
        widget: "list"
        min: 4
        max: 4
        fields: 
          - {label: "Nome do projeto", name: "projeto_destaque", widget: "relation", collection: "projetos", search_fields: ["nome_projeto"], value_field: "{{nome_projeto}}", display_fields: ["{{nome_projeto}}"]}
          - {label: "Título", name: "titulo_projeto", widget: "string"}
          - {label: "Subtítulo", name: "subtitulo_projeto", widget: "string"}
      
      - label: "Projetos para o carrossel"
        name: "portfolio_carrossel"
        collapsed: false
        widget: "list"
        min: 1
        max: 5
        fields:
          - {label: "Projeto", name: "projeto_carrossel", widget: "relation", collection: "projetos", search_fields: ["nome_projeto"], value_field: "{{nome_projeto}}", display_fields: ["{{nome_projeto}}"]}

  - name: "membros" # Nome usado da rota
    extension: "json"
    description: "Coleção que vai conter todos os membros da Faísca."
    label: "Membros" # Nome usado na label do Netlify 
    folder: "content/membros" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    editor:
      preview: false
    slug: "{{fields.nome_membro}}" 
    fields: 
      - {label: "Nome", name: "nome_membro", widget: "string"}
      - {label: "Cargo", name: "cargo_membro", widget: "relation", collection: "cargos", search_fields: ["cargo"], value_field: "{{cargo}}"}
      - {label: "Foto", name: "foto_membro", widget: "image"}

  - name: "cargos" # Nome usado da rota
    extension: "json"
    description: "Coleção que vai conter todos os cargos da Faísca."
    label: "Cargos" # Nome usado na label do Netlify 
    folder: "content/cargos" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    editor:
      preview: false
    slug: "{{fields.cargo}}" 
    fields: 
      - {label: "Cargo", name: "cargo", widget: "string"}

  - name: "servicos" # Nome usado da rota
    extension: "json"
    description: "Coleção que vai conter todos os serviços ofertados pela Faísca."
    label: "Serviços" # Nome usado na label do Netlify 
    folder: "content/servicos" # Local da pasta onde vão estar os arquivos
    create: true # Permite que usuários criem arquivos nesse local
    editor:
      preview: false
    slug: "{{fields.servico}}" 
    fields: 
      - {label: "Serviço", name: "servico", widget: "string"}

  - name: "projetos"
    extension: "json"
    description: "Coleção que vai conter os projetos da Faísca."
    label: "Projetos"
    folder: "content/projetos"
    create: true
    editor:
      preview: false
    slug: "{{fields.nome_projeto}}"
    fields:
      - {label: "Nome do projeto", name: "nome_projeto", widget: "string"}
      - {label: "Imagem de capa", name: "imagemCapa", widget: "image"}
      - {label: "Imagem sub-capa", name: "imagemSubCapa", widget: "image"}
      - {label: "Propósito do projeto", name: "textoPurpose", widget: "markdown"}
      - {label: "Serviço 1", name: "t1Services", widget: "string"}
      - {label: "Serviço 2", name: "t2Services", widget: "string"}
      - {label: "Serviço 3", name: "t3Services", widget: "string"}
      - {label: "Imagem serviço esquerda", name: "imageLeftSer", widget: "image"}
      - {label: "Imagem serviço direita", name: "imageRightSer", widget: "image"}
      - {label: "Imagem serviço inferior", name: "imageBottomSer", widget: "image"}
      - {label: "Valor 1", name: "t1Values", widget: "string"}
      - {label: "Valor 2", name: "t2Values", widget: "string"}
      - {label: "Valor 3", name: "t3Values", widget: "string"}
      - {label: "Imagem valor esquerda", name: "imageLeftVal", widget: "image"}
      - {label: "Imagem valor direita", name: "imageRightVal", widget: "image"}
      - {label: "Gerente do projeto", name: "gerente", widget: "relation", collection: "membros", search_fields: ["nome_membro"], value_field: "{{nome_membro}}", display_fields: ["{{nome_membro}} - {{cargo_membro}}"]}
      - label: "Projetistas envolvidos"
        name: 'projetistas'
        widget: "list"
        min: 1
        max: 2
        field: {label: "Projetista", name: "projetista", widget: "relation", collection: "membros", search_fields: ["nome_membro"], value_field: "{{nome_membro}}", display_fields: ["{{nome_membro}} - {{cargo_membro}}"]}
      - {label: "Texto do botão", name: "bottonText", widget: "string", default: "veja mais no nosso behance!"}
      - {label: "Link do Behance", name: "behanceLink", widget: "string"}
      - label: "Projetos relacionados (irão para o carrossel)"
        name: "relacionados_projetos"
        widget: "list"
        min: 1
        max: 5
        field: {label: "Projeto", name: "projeto_carrossel", widget: "relation", collection: "projetos", search_fields: ["nome_projeto"], value_field: "{{nome_projeto}}", display_fields: ["{{nome_projeto}}  {{imagemCapa}}"]}